spring:
  jpa:
    hibernate:
      ddlAuto: create-drop

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: postgres1
    password: bitclave1

hybrid:
  nodeUrl: http://localhost:9545/
  ownerPrivateKey: '0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501200'

  contracts:
    nameService:
      address: '0x0f5ea0a652e851678ebf77b69484bfcd31f9459b'
      gasPrice: '8000000'
      gasLimit: '8000000'
