spring:
  jpa:
    hibernate:
      ddlAuto: create-drop

  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: bitclave

server:
  port: 8080

hybrid:
  nodeUrl: http://localhost:9545/
  ownerPrivateKey: '0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501200'

  contracts:
    nameService:
      address: '0x0f5ea0a652e851678ebf77b69484bfcd31f9459b'
      gasPrice: '8000000'
      gasLimit: '8000000'
